#!/bin/bash

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#
chunkc core::hotload 1
chunkc core::unload tiling.so
chunkc core::unload ffm.so
chunkc core::unload border.so

chunkc set custom_bar_enabled            0
chunkc set custom_bar_all_monitors       1
chunkc set custom_bar_offset_top         22
chunkc set custom_bar_offset_bottom      0
chunkc set custom_bar_offset_left        0
chunkc set custom_bar_offset_right       0

# NOTE: the following are config variables for the chunkwm-tiling plugin.
#
# chunkc set global_desktop_mode <option>
# <option>: bsp | monocle | float
chunkc set global_desktop_mode           float


chunkc set global_desktop_offset_top     0
chunkc set global_desktop_offset_bottom  0
chunkc set global_desktop_offset_left    0
chunkc set global_desktop_offset_right   0
chunkc set global_desktop_offset_gap     15


chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5

chunkc set monitor_focus_cycle           0
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           0
chunkc set window_float_next             1
chunkc set window_float_center           0
chunkc set window_region_locked          1

chunkc set mouse_modifier                fn

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        0
chunkc set preselect_border_radius       0

chunkc set focused_border_color          0xff0f6288
chunkc set focused_border_width          0
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  0

chunkc set window_float_topmost          1
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.01
chunkc set window_use_cgs_move           1

#
# NOTE: specify plugins to load when chunkwm starts.
#       if chunkc plugin_dir is not set, the absolutepath is necessary.
#

# chunkc core::load border.so
chunkc core::load tiling.so

chunkc tiling::rule --owner Finder --name Copy --state float &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --owner Emacs --state float &
chunkc tiling::rule --owner Simulator --state float
