#!/usr/bin/env zsh

autoload -Uz vcs_info
autoload -U add-zsh-hook
# autoload -Uz async && async

setopt PROMPT_SUBST
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats " %b"

add-zsh-hook precmd precmd_vcs_info
add-zsh-hook precmd __prompt

prompt_line_sep=$'\n'
precmd_vcs_info() { vcs_info }

__format_cwd() {
  local dir_limit="3"
  local truncation="…"
  local first_char
  local part_count=0
  local formatted_cwd=""
  local dir_sep=" "
  local tilde="~"

  local cwd="${PWD/#$HOME/$tilde}"

  # get first char of the path, i.e. tilde or slash
  [[ -n ${ZSH_VERSION-} ]] && first_char=$cwd[1,1] || first_char=${cwd::1}

  # remove leading tilde
  cwd="${cwd#\~}"

  while [[ "$cwd" == */* && "$cwd" != "/" ]]; do
    # pop off last part of cwd
    local part="${cwd##*/}"
    cwd="${cwd%/*}"

    formatted_cwd="$dir_sep$part$formatted_cwd"
    part_count=$((part_count+1))

    [[ $part_count -eq $dir_limit ]] && first_char="$truncation" && break
  done
  printf "%s" "$first_char$formatted_cwd"
}

left_prompt() {
  local slice_prefix
  local slice_empty_prefix
  local slice_joiner
  local slice_suffix
  local is_prompt_empty=1

  # section "a" header
  slice_prefix="${a_bg}${sep}${a_fg}${a_bg}${space}"
  slice_suffix="$space${a_sep_fg}"
  slice_joiner="${a_fg}${a_bg}${alt_sep}${space}"
  slice_empty_prefix="${a_fg}${a_bg}${space}"

  [ $is_prompt_empty -eq 1 ] && slice_prefix="$slice_empty_prefix"

  # section "a" slices
  __segment_wrapper "$(__format_cwd)" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }

  # section "b" header
  slice_prefix="${b_bg}${sep}${b_fg}${b_bg}${space}"
  slice_suffix="$space${b_sep_fg}"
  slice_joiner="${b_fg}${b_bg}${alt_sep}${space}"
  slice_empty_prefix="${b_fg}${b_bg}${space}"

  [ $is_prompt_empty -eq 1 ] && slice_prefix="$slice_empty_prefix"

  # section "b" slices
  __segment_wrapper "$(vcs_branch)" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }

  # section "c" header
  slice_prefix="${c_bg}${sep}${c_fg}${c_bg}${space}"
  slice_suffix="$space${c_sep_fg}"
  slice_joiner="${c_fg}${c_bg}${alt_sep}${space}"
  slice_empty_prefix="${c_fg}${c_bg}${space}"

  [ $is_prompt_empty -eq 1 ] && slice_prefix="$slice_empty_prefix"

  # section "c" slices
  __segment_wrapper "$(__async_git_status)" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }

  printf "%s" "${reset_bg}${sep}$reset$space${prompt_line_sep}\$$space"
}

__segment_wrapper() {
  # wrap the text in $1 with $2 and $3, only if $1 is not empty
  # $2 and $3 typically contain non-content-text, like color escape codes and separators

  [[ -n "$1" ]] || return 1
  printf "%s" "${2}${1}${3}"
}

# Get branch
vcs_branch() {
  printf "${vcs_info_msg_0_}"
}

# Gets git diff status
__async_git_status() {
  [[ $(git rev-parse --is-inside-work-tree 2>/dev/null) == true ]] || return 1

  local added_symbol="• "
  local unmerged_symbol="ⅹ"
  local modified_symbol="+"
  local clean_symbol=""
  local has_untracked_files_symbol="…"

  local ahead_symbol="↑"
  local behind_symbol="↓"

  local unmerged_count=0 modified_count=0 has_untracked_files=0 added_count=0 is_clean=""

  set -- $(git rev-list --left-right --count @{upstream}...HEAD 2>/dev/null)
  local behind_count=$1
  local ahead_count=$2

  # Added (A), Copied (C), Deleted (D), Modified (M), Renamed (R), changed (T), Unmerged (U), Unknown (X), Broken (B)
  while read line; do
    case "$line" in
      M*) modified_count=$(( $modified_count + 1 )) ;;
      U*) unmerged_count=$(( $unmerged_count + 1 )) ;;
    esac
  done < <(git diff --name-status)

  while read line; do
    case "$line" in
      *) added_count=$(( $added_count + 1 )) ;;
    esac
  done < <(git diff --name-status --cached)

  if [ -n "$(git ls-files --others --exclude-standard)" ]; then
    has_untracked_files=1
  fi

  if [ $(( unmerged_count + modified_count + has_untracked_files + added_count )) -eq 0 ]; then
    is_clean=1
  fi

  local leading_whitespace=""
  [[ $ahead_count -gt 0 ]]         && { printf "%s" "$leading_whitespace$ahead_symbol$ahead_count"; leading_whitespace=" "; }
  [[ $behind_count -gt 0 ]]        && { printf "%s" "$leading_whitespace$behind_symbol$behind_count"; leading_whitespace=" "; }
  [[ $modified_count -gt 0 ]]      && { printf "%s" "$leading_whitespace$modified_symbol$modified_count"; leading_whitespace=" "; }
  [[ $unmerged_count -gt 0 ]]      && { printf "%s" "$leading_whitespace$unmerged_symbol$unmerged_count"; leading_whitespace=" "; }
  [[ $added_count -gt 0 ]]         && { printf "%s" "$leading_whitespace$added_symbol$added_count"; leading_whitespace=" "; }
  [[ $has_untracked_files -gt 0 ]] && { printf "%s" "$leading_whitespace$has_untracked_files_symbol"; leading_whitespace=" "; }
  [[ $is_clean -gt 0 ]]            && { printf "%s" "$leading_whitespace$clean_symbol"; leading_whitespace=" "; }
}

__prompt() {
  local esc=$'['
  local end_esc=m
  local noprint='%{'
  local end_noprint='%}'
  local wrap="$noprint$esc"
  local end_wrap="$end_esc$end_noprint"
  local space=" "
  local sep=""
  local rsep=""
  local alt_sep=""
  local alt_rsep=""
  local reset="${wrap}0${end_wrap}"
  local reset_bg="${wrap}49${end_wrap}"

  local a_fg="${wrap}38;5;015${end_wrap}"
  local a_bg="${wrap}48;5;4${end_wrap}"
  local a_sep_fg="${wrap}38;5;4${end_wrap}"

  local b_fg="${wrap}38;5;7${end_wrap}"
  local b_bg="${wrap}48;5;237${end_wrap}"
  local b_sep_fg="${wrap}38;5;237${end_wrap}"

  local c_fg="${wrap}38;5;7${end_wrap}"
  local c_bg="${wrap}48;5;238${end_wrap}"
  local c_sep_fg="${wrap}38;5;238${end_wrap}"

  PROMPT="$(left_prompt)"
}
